# .github/workflows/tests.yml

name: Ejecutar pruebas unitarias

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test